// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PMIS.Database;

#nullable disable

namespace CustomerOrderManagementApp.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20241120094439_Order_Create_Model")]
    partial class Order_Create_Model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PMIS.Models.EntityModels.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AddressCity")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Gender")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.CustomerCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("CustomersCategories");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeIDNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EmployeeOfficialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeOfficialId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.EmployeeOfficial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("EmployeeOfficial");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.PersonalInformation", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("BankAccountInfo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("HomeDistrict")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("IdentificationMark")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MothersName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NIDNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("NoOfChildren")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PresentAddress")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Religion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SpousesName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SpousesOccupation")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TelephoneNo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EmployeeId");

                    b.ToTable("PersonalInformation");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.Customer", b =>
                {
                    b.HasOne("PMIS.Models.EntityModels.CustomerCategory", "Category")
                        .WithMany("Customers")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.Employee", b =>
                {
                    b.HasOne("PMIS.Models.EntityModels.EmployeeOfficial", "EmployeeOfficial")
                        .WithMany()
                        .HasForeignKey("EmployeeOfficialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeOfficial");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.PersonalInformation", b =>
                {
                    b.HasOne("PMIS.Models.EntityModels.Employee", "Employee")
                        .WithOne("PersonalInformation")
                        .HasForeignKey("PMIS.Models.EntityModels.PersonalInformation", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.CustomerCategory", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("PMIS.Models.EntityModels.Employee", b =>
                {
                    b.Navigation("PersonalInformation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
